name: MyFirstWorkflow
on:
  push:
    branches: 
      - main
  workflow_dispatch:
jobs:
  myFirstJob:
    runs-on: ubuntu-latest

    steps: 
      - run: echo "Hello World from my first github action"
      
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Lists file in the repo
        run: |
          echo "The repository ${{ github.repository  }} contains the following files:"
          tree
        
